spring:
  application:
    name: parking-ctrl
  datasource:
    url: jdbc:postgresql://localhost:5432/parking-ctrl-db
    username: postgres
    password: Tu@irm@5@f@d@
    driver-class-name: org.postgresql.Driver
  # JPA / Hibernate Configuration
  # vou deixar create-drop para testar, mas em produção deve ser alterado para validate (vem inicialmente como update)
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': true